[index]

== Working with Collections

While cyclops-react doesn't implement any collection types directly itself, it does provide a very poweful series of extension methods over existing JDK collection interfaces (with plugable implementations). As we shall see cyclops-react provides a very powerful stream-like interface into mutable, immutable and persistent collections - all while extending the existing JDK interfaces.

=== Collection eXenstions

cyclops-react provides extensions for Lists, Sets, Maps, SortedSets, Queues and Deques, these are

1. ListX
1. SetX
1. SortedSetX
1. QueueX
1. DequeX
1. MapX

With Collection eXtensions we convert verbose Java code into much more terse equivalents.

.Java 8 to ListX
====

[source,java]
----
 Arrays.asList(new Person(10))
              .stream()
              .collect(Collectors.groupingBy(Person::getAge));
----

The equivalent code with ListX, looks like this 

[source,java]
----
ListX.of(new Person(10))
             .groupBy(Person::getAge);
----
====

== Additional libraries and eXtensions

cyclops-react also does leverage three libraries with a number of very useful collection types to make modern functional-style and asynchronous programming easier.


Those libs are

1. PCollections : PCollections provides persistent collections that implement the standard JDK Collection interfaces. add / remove / put based methods are deprecated and alternatives - plus and minus are used instead.
1. Agrona : Agrona provide a number of advanced concurrent collections, such as various wait-free queues and ring-buffers.
1. jOOλ Tuples

== PCollections

http://pcollections.org[From PCollections.org]
[NOTE]
====
PCollections serves as a persistent and immutable analogue of the Java Collections Framework. This includes *efficient*, *thread-safe*, *generic*, *immutable*, and *persistent* stacks, maps, vectors, sets, and bags, *compatible* with their Java Collections counterparts.

Persistent and immutable datatypes are increasingly appreciated as a simple, design-friendly, concurrency-friendly, and sometimes more time- and space-efficient alternative to mutable datatypes.
====

==== Collections

cyclops-react provides a package (com.aol.cyclops-react.collections) filled with companion classes for creating instances of PCollections. Each companion class offers handy methods for collection creation and conversion (reduction) from a Stream.

We provide mechanisms for generating both extended pCollections (such as PStackX, PVectorX, POrderedSetX, PQueueX, PMapX, PBagX) and non-extended pCollections.

===== PMaps

PMaps are persistent equivalents of JDK HashMaps.

===== PStacks

PStacks are persistent equivalents of JDK LinkedLists.

[IMPORTANT]
====
For efficiency reasons, PStack prepends values to the PStack when plusAll is called, this results in reversed order PStacks when created from Streams.
====

.create PStacks
====
[source,java]
----
PStack<String> list = PStacks.of("a","b","c");
PStack<String> list = PStacks.fromCollection(Arrays.asList("a","b","c"));
List<String> empty = PStacks.empty();
PStack<String> single = PStacks.singleton("1");
----
====

.convert a Stream to a PStack
====
[source,java]
----
PStackX<Integer> list = PStackX.fromStream(Stream.of(1,2,3));
PStack<Integer> list = PStacks.fromStream(Stream.of(1,2,3));
 //list = [3,2,1]
 
PStackX<String> list = ReactiveSeq.of("a","b","c").mapReduce(Reducers.toPStackX()) 
PStack<String> list = ReactiveSeq.of("a","b","c").mapReduce(Reducers.toPStack())
//list = ["c","b","a"]

PStack<String> list = PStacks.toPStack().reduce(Stream.of("a","b","c")));
//list = ["c","b","a"]
----
====

===== PVectors

[IMPORTANT]
====
Unlike PStacks, PVector append new data to the persistent List when plusAll is called.
====

.create PVectors
====
[source,java]
----
PVectorX<String> list = PVectorX.of("a","b","c");
PVector<String> list = PVectors.of("a","b","c");
List<String> empty = PVectors.empty();
PVectorX<String> single = PVectorX.singleton("1");
PVector<String> single = PVectors.singleton("1");
PVector<String> list = PVector.fromCollection(Arrays.asList("a","b","c"));
----
====

.convert a Stream to a PVector
====
[source,java]
----
PVectorX<Integer> list = PVectorX.fromStream(Stream.of(1,2,3));
PVector<Integer> list = PVectors.fromStream(Stream.of(1,2,3));
 //list = [1,2,3]
 
PVector<String> list = SequenceM.of("a","b","c").mapReduce(PVectors.toPVector()
//list = ["a","b","c"]

PVector<String> list = PVectors.toPVector().reduce(Stream.of("a","b","c")));
//list = ["a","b","c"]
----
====
===== PSets

.create PSets
====
[source,java]
----
PSetX<String> list = PSetX.of("a","b","c");

Set<String> empty = PSets.empty();

----
====

.convert a Stream to a PSet
====
[source,java]
----
PSetX<Integer> list = PSetX.fromStream(Stream.of(1,2,3));
----
====
===== PBags
.create PBags
====
[source,java]
----
PBagX<String> list = PBagX.of("a","b","c");

Collection<String> empty = PBags.empty();

----
====

.convert a Stream to a PBag
====
[source,java]
----
PBagX<Integer> list = PBagX.fromStream(Stream.of(1,2,3));
----
====
===== PQueues
.create PQueues
====
[source,java]
----
PQueueX<String> list = PQueueX.of("a","b","c");

Queue<String> empty = PQueues.empty();

----
====

.convert a Stream to a PQueue
====
[source,java]
----
PQueueX<Integer> list = PQueueX.fromStream(Stream.of(1,2,3));
----
====
===== OrderedPSets
.create OrderedPSets
====
[source,java]
----
POrderedSetX<String> list = POrderedSetX.of("a","b","c");

Set<String> empty = POrderedSets.empty();

----
====

.convert a Stream to a PQueue
====
[source,java]
----
POrderedSetsX<Integer> list = POrderedSetsX.fromStream(Stream.of(1,2,3));
----
====

==== Reducers

The Reducers class provides a number of Reducers useful for geerating persistent collecitons. Mutable JDK collections are best generated from a stream via the mutable reduction collect method. Persistent collections are generally best created via standard immutable reduction. As reduction operations must be performed on Objects of the same type, Reducer implementations also provide a mechanism to map from any type to the target type. I.e. The Reducer for PStacks can convert every element to a PStack for combination.


== Agrona

https://github.com/real-logic/Agrona[From https://github.com/real-logic/Agrona]
[NOTE]
====
Agrona provides a library of data structures and utility methods that are a common need when building high-performance applications in Java. Many of these utilities are used in the https://github.com/real-logic/Aeron[Aeron] efficient reliable UDP unicast, multicast, and IPC message transport.
====
