package com.aol.cyclops.sequence;

import com.aol.cyclops.sequence.streamable.ConvertableToSequenceM;

public interface JoolWindowing<T> extends ConvertableToSequenceM<T>{
	public default org.jooq.lambda.Seq org.jooq.lambda.Seq.window(org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification)
	public default org.jooq.lambda.Seq org.jooq.lambda.Seq.window(org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification)
	public default org.jooq.lambda.Seq org.jooq.lambda.Seq.window(org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification)
	public default org.jooq.lambda.Seq org.jooq.lambda.Seq.window(org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification)
	public default org.jooq.lambda.Seq org.jooq.lambda.Seq.window(org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification)
	public default org.jooq.lambda.Seq org.jooq.lambda.Seq.window(java.util.function.Function)
	public default org.jooq.lambda.Seq org.jooq.lambda.Seq.window(java.util.Comparator,long,long)
	public default org.jooq.lambda.Seq org.jooq.lambda.Seq.window(java.util.Comparator)
	public default org.jooq.lambda.Seq org.jooq.lambda.Seq.window(org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification)
	public default org.jooq.lambda.Seq org.jooq.lambda.Seq.window(java.util.function.Function,long,long)
	public default org.jooq.lambda.Seq org.jooq.lambda.Seq.window(java.util.function.Function,java.util.Comparator)
	public default org.jooq.lambda.Seq org.jooq.lambda.Seq.window(java.util.function.Function,java.util.Comparator,long,long)
	public default org.jooq.lambda.Seq org.jooq.lambda.Seq.window(org.jooq.lambda.WindowSpecification)
	public default org.jooq.lambda.Seq org.jooq.lambda.Seq.window(org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification)
	public default org.jooq.lambda.Seq org.jooq.lambda.Seq.window(org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification)
	public default org.jooq.lambda.Seq org.jooq.lambda.Seq.window(long,long)
	public default org.jooq.lambda.Seq org.jooq.lambda.Seq.window(org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification)
	public default org.jooq.lambda.Seq org.jooq.lambda.Seq.window(org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification)
	public default org.jooq.lambda.Seq org.jooq.lambda.Seq.window(org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification)
	public default org.jooq.lambda.Seq org.jooq.lambda.Seq.window(org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification)
	public default org.jooq.lambda.Seq org.jooq.lambda.Seq.window(org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification)
	public default org.jooq.lambda.Seq org.jooq.lambda.Seq.window()
	public default org.jooq.lambda.Seq org.jooq.lambda.Seq.window(org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification)
	public default org.jooq.lambda.Seq org.jooq.lambda.Seq.window(org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification,org.jooq.lambda.WindowSpecification)

}
